# news/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import (
    # ViewSets
    ArticleViewSet,
    PublisherViewSet,
    UserViewSet,
    NewsletterViewSet,
    # Extra endpoints
    ArticleApproveView,
    SubscriptionFeedView,
    # (Keep any other helpers you already had)
    api_subscribed_articles,
    api_publisher_articles,
    api_journalist_articles,
)

# DRF router
router = DefaultRouter()
# basename = "api-article" gives the names api-article-list & api-article-detail
router.register(r"articles", ArticleViewSet, basename="api-article")
router.register(r"publishers", PublisherViewSet, basename="publisher")
router.register(r"users", UserViewSet, basename="user")
router.register(r"newsletters", NewsletterViewSet, basename="newsletter")

# Final urlpatterns
urlpatterns = [
    # All CRUD routes generated by the router
    *router.urls,

    # POST /api/articles/<pk>/approve/
    path(
        "articles/<int:pk>/approve/",
        ArticleApproveView.as_view(),
        name="api-article-approve",
    ),

    # GET /api/subscriptions/feed/
    path(
        "subscriptions/feed/",
        SubscriptionFeedView.as_view(),
        name="api-subscription-feed",
    ),

    # Other helper endpoints
    path(
        "subscribed-articles/",
        api_subscribed_articles,
        name="api_subscribed_articles",
    ),
    path(
        "publisher/<int:publisher_id>/articles/",
        api_publisher_articles,
        name="api_publisher_articles",
    ),
    path(
        "journalist/<int:journalist_id>/articles/",
        api_journalist_articles,
        name="api_journalist_articles",
    ),
]
